### ISSUE TITLE
ERROR：build the dockerfile

### ISSUE THREAD

**Issue by cir2001** [hucebot/opensot_docker#1]
Hi,
I tried to build the Dockerfile, using the "docker build -t opensot .", and during the build process, the following error occurred, and the computer crashed and stopped responding:
------------------------------------------------------------------------------------------------------------------------------------
[  4%] Building CXX object src/CMakeFiles/pinocchio_default.dir/algorithm/compute-all-terms.cpp.o
cd /home/forest_ws/build/pinocchio/src && /usr/bin/c++  -DBOOST_MPL_LIMIT_LIST_SIZE=30 -DBOOST_MPL_LIMIT_VECTOR_SIZE=30 -DPINOCCHIO_CONTEXT_FILE=\"pinocchio/context/default.hpp\" -DPINOCCHIO_ENABLE_TEMPLATE_INSTANTIATION -Dpinocchio_EXPORTS -I/home/forest_ws/build/pinocchio -I/home/forest_ws/build/pinocchio/include -I/home/forest_ws/src/pinocchio/include -isystem /usr/include/eigen3  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -O3 -DNDEBUG -fPIC   -std=gnu++14 -o CMakeFiles/pinocchio_default.dir/algorithm/compute-all-terms.cpp.o -c /home/forest_ws/src/pinocchio/src/algorithm/compute-all-terms.cpp
/home/forest_ws/src/pinocchio/include/pinocchio/algorithm/constrained-dynamics.hxx: In instantiation of 'const typename pinocchio::DataTpl<_Scalar, Options, JointCollectionTpl>::TangentVectorType& pinocchio::contactABA(const pinocchio::ModelTpl<Scalar, Options, JointCollectionTpl>&, pinocchio::DataTpl<Scalar, Options, JointCollectionTpl>&, const Eigen::MatrixBase<Matrix3Like>&, const Eigen::MatrixBase<MatRet>&, const Eigen::MatrixBase<VectorLike>&, const std::vector<pinocchio::RigidConstraintModelTpl<Scalar, Options>, ConstraintModelAllocator>&, std::vector<pinocchio::RigidConstraintDataTpl<Scalar, Options>, ConstraintDataAllocator>&, pinocchio::ProximalSettingsTpl<Scalar>&) [with Scalar = double; int Options = 0; JointCollectionTpl = pinocchio::JointCollectionDefaultTpl; ConfigVectorType = Eigen::Matrix<double, -1, 1>; TangentVectorType1 = Eigen::Matrix<double, -1, 1>; TangentVectorType2 = Eigen::Matrix<double, -1, 1>; ModelAllocator = Eigen::alignedallocator<pinocchio::RigidConstraintModelTpl<double, 0> >; DataAllocator = Eigen::aligned_allocator<pinocchio::RigidConstraintDataTpl<double, 0> >; typename pinocchio::DataTpl<_Scalar, _Options, JointCollectionTpl>::TangentVectorType = Eigen::Matrix<double, -1, 1>]':
/home/forest_ws/src/pinocchio/include/pinocchio/algorithm/constrained-dynamics.hpp:186:22:   required from 'const typename pinocchio::DataTpl<_Scalar, Options, JointCollectionTpl>::TangentVectorType& pinocchio::contactABA(const pinocchio::ModelTpl<Scalar, Options, JointCollectionTpl>&, pinocchio::DataTpl<Scalar, Options, JointCollectionTpl>&, const Eigen::MatrixBase<Matrix3Like>&, const Eigen::MatrixBase<MatRet>&, const Eigen::MatrixBase<VectorLike>&, const std::vector<pinocchio::RigidConstraintModelTpl<Scalar, Options>, ConstraintModelAllocator>&, std::vector<pinocchio::RigidConstraintDataTpl<Scalar, Options>, ConstraintDataAllocator>&) [with Scalar = double; int Options = 0; JointCollectionTpl = pinocchio::JointCollectionDefaultTpl; ConfigVectorType = Eigen::Matrix<double, -1, 1>; TangentVectorType1 = Eigen::Matrix<double, -1, 1>; TangentVectorType2 = Eigen::Matrix<double, -1, 1>; ModelAllocator = Eigen::alignedallocator<pinocchio::RigidConstraintModelTpl<double, 0> >; DataAllocator = Eigen::aligned_allocator<pinocchio::RigidConstraintDataTpl<double, 0> >; typename pinocchio::DataTpl<_Scalar, _Options, JointCollectionTpl>::TangentVectorType = Eigen::Matrix<double, -1, 1>]'
/home/forest_ws/src/pinocchio/src/algorithm/constrained-dynamics.cpp:73:41:   required from here
/home/forest_ws/src/pinocchio/include/pinocchio/algorithm/constrained-dynamics.hxx:867:10: warning: variable 'optimal_solution_found' set but not used [-Wunused-but-set-variable]
  867 |     bool optimal_solution_found = false;
      |          ^~~~~~~~~~~~~~~~~~~~~~
------------------------------------------------------------------------------------------------------------------------------------
What should I do to install it correctly?

**Comment by EnricoMingo** [comment]
Dear @cir2001, this should be a simple warning, it should not cause the compilation to abort. The `Pinocchio` library may takes some time to compile. 

According to the number of cores in your laptop, you could try to set a smaller number in the [DockerFile](https://github.com/hucebot/opensot_docker/blob/15870e5eaaa91bb5f72c9059404f6a69cf32b149/Dockerfile#L92). For example you could use `-j4` and check if it does not crash. However, you should have the cache until that step.

**Comment by cir2001** [comment]
Dear@EnricoMingo, I followed your suggestion, and it has been worked, thank you very much.
