### ISSUE TITLE
Mobile manipulation guidance

### ISSUE THREAD

**Issue by cir2001** [hucebot/opensot_docker#2]
Dear@EnricoMingo，
I want to use OpenSoT to control mobile manipulation using Python. I have implemented the panda test program in Docker. What should I do next?
I tried to change the world joint in urdf to floating mode, but it failed to load panda when I opened rviz.
My idea is to let panda float freely in the world coordinate system first, and then load the mobile manipulation model.
I don't know if my idea is correct, and I hope to get your guidance. Thank you!

**Comment by EnricoMingo** [comment]
Hi @cir2001, could you please post the error you get from the terminal?

**Comment by EnricoMingo** [comment]
Hi @cir2001, here you have 2 issues, let's see them one by one.

First, the panda model loaded in the OpenSoT python panda example `panda_ik.py` is the one contained in `franka_cartesio_config/urdf/panda.urdf.xacro`. To add the floating base to this model you just  change:

`<joint name="world_joint" type="fixed">`

to

`<joint name="world_joint" type="floating">`

Once you have done this, check the number of dofs and joint velocities, you should have 14 dofs and 13 joint velocities.
The floating base orientation is parameterized through a quaternion there fore you can not anymore add the output of opensot to the state:

`q += dq`

but you need to use a proper integration method on the quaternion manifold:

`q = model.sum(q, dq)`.

Finally, the message with the joint states does not contain the floating base part, that one you will need to publish as a `tf` transform (using a tf publisher), converting the quaternion part into a rotation. If you check the final part of the code in the `LittleDog_id.py` you should have an idea on how to do it. 

Please try first these things and then we can check the DART thing.
