### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cir2001** [hucebot/opensot_docker#3]
Dear@EnricoMingo，
I hope I can describe the problem accurately. If there are any inaccuracies, I hope you can point them out.
I am working on WBC of mobile manipulation. Now I can use OpenSOT's floating coordinate mode to move the manipulation independently in the world coordinate system and solve the joint position.
I want to try to do a separate wbc for mobile first, by setting
`c = Cartesian("Cartesian", model, "base_link", "world")`
given the target position
```
pose_ref.translation[0] = 1.0
pose_ref.translation[1] = 1.5
pose_ref.translation[2] = 0.
```
Using opensot to solve the joints, the joint information has not changed, it is the given initial value, and the coordinate position is tracking the given position
```
q [0.99999887 1.49999831 0. 0. 0. 0.
1. 0. 0. 0. 0. 0.
0. 0. 0. ]
```
but the position of each joint is not solved

May I ask,
Is it correct to solve the joint position of the four wheels of the mobile by setting the target position of base_link through opensot? How can I get the joint angles of the four wheels given the base_link position in the WBC way?

Can opensot perform inverse kinematics solution for mobile, or do I need to use my own inverse kinematics solver to achieve it?

What should I do to conduct WBC on mobile manipulation?
Hope to get your guidance

**Comment by EnricoMingo** [comment]
Hi @cir2001, what type of mobile base are you using? Can you explain to me the q state what does it represent? I can recognize the floating base part (first 7 values) but the reset what does they represent? The manipulator generalized coordinates?

**Comment by cir2001** [comment]
Hi@EnricoMingo，
I use a custom generated urdf mobile car
```
<?xml version="1.0"?>
<robot name="large_four_wheel_robot">
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="red">
    <color rgba="1 0 0 1"/>
  </material>
  <material name="green">
    <color rgba="0 0.8 0 1"/>
  </material>

  <!-- World Link -->
  <link name="world"/>

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="1.0 0.8 0.2"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="1.0 0.8 0.2"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="50"/>
      <inertia ixx="3.42" ixy="0" ixz="0" iyy="5.0" iyz="0" izz="8.08"/>
    </inertial>
  </link>

  <!-- Floating Joint between World and Base Link -->
  <joint name="floating_joint" type="floating">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <!-- 底盘位置参考点 -->
  <link name="chassis_position">
    <visual>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="chassis_position_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis_position"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- Front Left Wheel -->
  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5"/>
      <inertia ixx="0.0290" ixy="0" ixz="0" iyy="0.0290" iyz="0" izz="0.0563"/>
    </inertial>
  </link>

  <joint name="front_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_left_wheel"/>
    <origin xyz="0.45 0.45 -0.1" rpy="-1.5707 0 0"/>
    <axis xyz="0 0 1"/>
    <limit velocity="10" effort="100"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Front Right Wheel -->
  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5"/>
      <inertia ixx="0.0290" ixy="0" ixz="0" iyy="0.0290" iyz="0" izz="0.0563"/>
    </inertial>
  </link>

  <joint name="front_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_right_wheel"/>
    <origin xyz="0.45 -0.45 -0.1" rpy="-1.5707 0 0"/>
    <axis xyz="0 0 1"/>
    <limit velocity="10" effort="100"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Rear Left Wheel -->
  <link name="rear_left_wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5"/>
      <inertia ixx="0.0290" ixy="0" ixz="0" iyy="0.0290" iyz="0" izz="0.0563"/>
    </inertial>
  </link>

  <joint name="rear_left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_left_wheel"/>
    <origin xyz="-0.45 0.45 -0.1" rpy="-1.5707 0 0"/>
    <axis xyz="0 0 1"/>
    <limit velocity="10" effort="100"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- Rear Right Wheel -->
  <link name="rear_right_wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.1" radius="0.15"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5"/>
      <inertia ixx="0.0290" ixy="0" ixz="0" iyy="0.0290" iyz="0" izz="0.0563"/>
    </inertial>
  </link>

  <joint name="rear_right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="rear_right_wheel"/>
    <origin xyz="-0.45 -0.45 -0.1" rpy="-1.5707 0 0"/>
    <axis xyz="0 0 1"/>
    <limit velocity="10" effort="100"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <!-- World Coordinate Frame Visual Indicator -->
  <link name="world_frame">
    <visual>
      <geometry>
        <box size="0.1 0.1 0.1"/>
      </geometry>
      <material name="green"/>
    </visual>
  </link>
  <joint name="world_frame_joint" type="fixed">
    <parent link="world"/>
    <child link="world_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
</robot>
```
The model only defines 4 joints, q=7+4, but after reading the urdf, q=7+8, which is also what I find strange

**Comment by EnricoMingo** [comment]
Ok, here we have 2 different things:
1. This car model makes use of _continuous joints_ which are parameterized through cos and sin of the angle (see [this issue](https://github.com/stack-of-tasks/pinocchio/issues/794)). For this reason, you see 8+7 numbers in the configuration space. 
This also means that you have to use the `sum` method, provided by the `ModelInterface` object, once you get the results from the optimization. This will permit to get, from the previous configuration and the new joint velocities, the new configuration, something like this:

```
/* Integrate solution */

    _model->getJointPosition(_q);

    _q = _model->sum(_q, _dq); \\dq is the solution from the solver
```
Basically, you should not manually handle the generalized coordinates of the robot but just get and set the values on the model.
Remember that in OpenSoT, velocity tasks are in `dq`, not `qdot`. 

2. Using a Cartesian task in the base to send velocity reference is fine, but you need to relate these velocities of the base to the velocity of the wheels. To do so you need some constraints, something like imposing a car-like or differential drive model for example. Notice that in the case of non-holonomic bases (e.g. car-ike, differential drive), you can not realize instantaneous velocity in all directions, please refer to the literature to see how to control this kind of system. Instead, if you have an omnidirectional base you can easily find out how to relate these velocities (see [this example](https://github.com/hucebot/tiago_dual_cartesio_config)).

**Comment by EnricoMingo** [comment]
Can we close this???

**Comment by cir2001** [comment]
sorry, it's late to close.
